### ISSUE TITLE
meta karten

### ISSUE THREAD

**Issue by lukruh** [telebotter/projekt47#13]
- [x] modelfield aufgedeckt ja/nein
- [x] impact 1-6 
- [x] karte als html/bild/pdf/text?
- [x] eine metakarte beinhaltet: Name, Beschreibung, (Bild?), Impact, medelfield

karten ideen in kommentaren

**Comment by lukruh** [comment]
- [x]  trinke einen kurzen für einen reroll?
- [x] Trinke sachen in der selben farbe oder so
- [x] Meta: reborn, wenn dein charakter stirbt, kehrt er zurück
- [ ] Meta, einmalig, bodyswap, wechsle deinen charakter, der gm erstellt ihn dir
- [x] Meta: tausche deine metakarte zu einem beliebigen zeitpunkt mit einer aus dem stapel
- [ ] Meta: lass mich mal, nach 2h spielzeit tauschst du mit dem GM/anderen Charakter die rollen
- [x] Meta, geh zum späti und hole ein paar getränke, wenn du wiederkommst steigst du mit +anzahl getränke skillpunkten in die geschichte ein
die selbe menge proviant steht auch der gruppe im spiel zur verfuegung
- [x] Meta, spielbeginn zeige was du kannst! Du hast 5 min zeit, iss so viele scheiben toastbrot wie du kannst, für jede scheibe bekommst du 2 extra skillpunkte. Deine intelligenz muss auf 6 bleiben!
- [x] Meta spielbeginn, fülle dein glas mit je einem schluck eines jeden getränks auf dem spieltisch/zimmer. Wenn du es runterbekommst ist dein charakter immun gegen gift
- [x] Meta blasenschwäche, um auf toilette gehen zu dürfen mache eine willenskraft probe
- [ ] Meta: spiele eine aktion pantomimisch nach, wird sie von der gruppe (im ersten versuch) erraten gelingt sie ohne zu wuerfeln. Nur einmal pro spiel einsetzbar
- [x] Meta, spätentwickler, nach dem spiel erhälst du die doppelte anzahl an skillpunkten die der gm dir gibt
- [x] Meta: niete
- [x] Platscher: nichts geschieht
- [ ] Meta: Fanatiker, Aeusserst du eine Idee versucht dien Charakter diese umzusetzten.
- [ ] Meta, mitläufer, aussert die gruppe eine idee beteiligt sich dein charakrer
- [ ] Meta: Rebell, aussert die gruppe eine idee protestiert dein charakter
- [ ] Meta, niemand mag klugscheisser, immer wenn du absets des spiels jemanden korregierst erscheint ein troll bewaffnet mit keule und versucht dir einen auf die rübe zu geben
Oder immer wenn du den gm versuchst zu überreden
oder du verlierst am ende des spiels einen skillpunkt den der korrigierte bekommt
- [x] Meta dj, kümmere dich um die musik. Wenn die gruppe genervt ist verlierst du eine skillpunkt auf geschmack
- [x] Meta kraftprotz, mache so viele liegestütze wie du in einer minute schaffst, pro 10 liegestütze bekommst du einen extra skillpunkt auf stärke. Muss jede stunde wiederholt werden
Meta, gedankenraub, deine beiden stitznachbarn geben dir jeweils ein skillpunkt intelligenz ab sofern vorhanden
- [ ] Meta, du bist du. Gm erstellt dich als charakter für dich
- [ ] Meta, akku, der spieler mit dem niedrigsten akkustand gibt einen skillpunkt auf ausdauer an den mit dem hoechsten akkustand ab
- [ ] meta,Kapuuut, deine skillpunkte werden stündlich zufällig verteilt (/randomize) deine fähigkeiten bleiben gleich
- [x] Meta, siegestrunk, trinke immer einen wenn du eine probe bestehst
- [x] Meta frustsaufen, trinke immer einen wenn du eine probe versaust

**Comment by lukruh** [comment]
Meta, gedankenraub, deine beiden stitznachbarn geben dir jeweils ein skillpunkt intelligenz ab sofern vorhanden

**Comment by lukruh** [comment]
Meta, du bist du. Gm erstellt dich als charakter für dich

**Comment by lukruh** [comment]
Meta, akku, der spieler mit dem niedrigsten akkustand gibt einen skillpunkt auf ausdauer an den mit dem hoechsten akkustand ab

**Comment by lukruh** [comment]
Hendrik Freiheit, [08.02.20 16:51]
meta,Kapuuut, deine skillpunkte werden stündlich zufällig verteilt (/randomize) deine fähigkeiten bleiben gleich

Hendrik Freiheit, [08.02.20 16:53]
Meta, siegestrunk, trinke immer einen wenn du eine probe bestehst

Hendrik Freiheit, [08.02.20 16:53]
Meta frustsaufen, trinke immer einen wenn du eine probe versaust

**Comment by hendricokakiko** [comment]
"wenigstends ein paar metakarten für den pre-release bereitstellen, eine /drawmetacard command implementieren"

**Comment by lukruh** [comment]
um ein random objekt aus der datenbank zu bekommen koennte folgender django orm befehl hilfreich sein:
``` MetaCard.objects.filter(addon=addon).sort_by('?').first()```

**Comment by hendricokakiko** [comment]
der befehl ist order_by.
befehl ist eingebaut - ich hab das addon nicht in die funktion importiert bekommen - dh er guckt sich jetzt alle vorhandenen metakarten an... auch gut - minor issue

**Comment by lukruh** [comment]
>  ich hab das addon nicht in die funktion importiert bekommen 

ist in der models.py und was ich noch haette erwaehen koennen, das projekt wird aus dem `telebotter/` ordner heraus gestartet, dh die models sind ueber den jeweiligen bot (modul) zu importieren.. sollte also 
```
from projekt47.models import Addon
```
sein. Ich hab mir  aber eh immer nur die instanz (konkretes addon) aus dem spieler geholt (die anderen interesseieren ja meistens nicht).. dann musste auch nichts importieren:
```
player = ut.get_p_user(update.from_user)
addon = player.active_char.addon
```

**Comment by lukruh** [comment]
denke es waere auch gut wenn die meta card im char gespeichert wird oder?

**Comment by lukruh** [comment]
hab sie im char gespeichert und ergaenzt, dass man sie angezeigt bekommt wenn man schon eine hat (nicht automatsich neue zieht) um neue zu ziehen, kann man `/metacard neu` eingeben.
Und paar kleinigkeiten angepasst.. addon, logging und codestyle. Ausserdem karte dem char.info_text hinzugefuegt.. oder soll es eher zu stats?
impact und face_down (verdeckt) hab ich auch noch als felder ergaenzt.. auch wenn wir sie erstmal nicht brauchen..

**Comment by lukruh** [comment]
denke damit waere closed?
